---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-a
  labels:
    type: local
    env: demo
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  nfs:
    server: 10.0.21.40
    path: /tmp/nfs/kubedata/pva
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-b
  labels:
    type: local
    env: demo
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  nfs:
    server: 10.0.21.40
    path: /tmp/nfs/kubedata/pvb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-c
  labels:
    type: local
    env: demo
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  nfs:
    server: 10.0.21.40
    path: /tmp/nfs/kubedata/pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-d
  labels:
    type: local
    env: demo
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  nfs:
    server: 10.0.21.40
    path: /tmp/nfs/kubedata/pvd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-e
  labels:
    type: local
    env: demo
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  nfs:
    server: 10.0.21.40
    path: /tmp/nfs/kubedata/pve
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-f
  labels:
    type: local
    env: demo
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  nfs:
    server: 10.0.21.40
    path: /tmp/nfs/kubedata/pvf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-networking
  labels:
    app: nginx
    env: demo
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webset
  labels:
    app: nginx
    env: demo
spec:
  serviceName: "nginx-networking"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      env: demo
  template:
    metadata:
      labels:
        app: nginx
        env: demo
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      storageClassName: local-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 200Mi