---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-elk-02
  namespace: elk
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pv02"