# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: statefulset
  labels:
    app: statefulset-app
spec:
  ports:
  - name: nginx
    port: 80
  clusterIP: None
  selector:
    app: statefulset-app